packages:
  - apps/*
  - packages/*
catalog:
  typescript: ^5.8.2
  "@biomejs/biome": ^1.9.4
  dotenv-cli: ^8.0.0
  "@tsconfig/node-lts": ^22.0.1
  "@tsconfig/node-ts": ^23.6.1
  tsx: ^4.19.3
  tsup: 8.3.0
  "@types/node": ^22
  "@types/pg": ^8.11.11
  "@trpc/client": ^11.0.0
  "@trpc/react-query": ^11.0.0
  "@trpc/server": ^11.0.0
  pg: ^8.14.1
  superjson: ^2.2.2
  zod: ^3.25.20
onlyBuiltDependencies:
  - "@biomejs/biome"
  - core-js-pure
  - esbuild
